# Generated by Django 4.1.4 on 2023-01-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartId',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='categoryId',
            new_name='category',
        ),
    ]
