# Generated by Django 4.1.4 on 2023-01-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_userid_cart_user_rename_cartid_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPickItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item', verbose_name='fk_item')),
                ('staffPick', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.staffpick', verbose_name='fk_cart')),
            ],
        ),
    ]
