# Generated by Django 4.1.4 on 2023-02-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart_guitarconfiguration_productcategory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='guitar_configuration',
        ),
        migrations.RemoveField(
            model_name='guitarconfiguration',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='guitarconfigurationitem',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='guitarconfigurationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='GuitarConfiguration',
        ),
        migrations.DeleteModel(
            name='GuitarConfigurationItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
