# Generated by Django 4.1.4 on 2023-01-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_staffpick_staffpickitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffPickItems',
            new_name='StaffPickItem',
        ),
    ]
