# Generated by Django 4.1.4 on 2023-03-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_item_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
