# Generated by Django 4.1.4 on 2023-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_configurationitem_configuration_alter_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='configuration_items',
        ),
        migrations.AddField(
            model_name='configuration',
            name='configuration_items',
            field=models.ManyToManyField(to='base.configurationitem'),
        ),
    ]
