# Generated by Django 4.1.4 on 2023-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
