# Generated by Django 4.1.4 on 2023-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_configuration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='configuration_items',
            field=models.ManyToManyField(to='base.item'),
        ),
    ]
