# Generated by Django 4.1.4 on 2023-03-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_configuration_configuration_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='configurations',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='configuration',
        ),
    ]
