# Generated by Django 4.1.4 on 2023-03-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurationItem',
        ),
    ]
